spring:
  application:
    name: advanced-web-sorting-algorithms
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update

application:
  secret: ${SECRET_KEY}
